name: UI
on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build frontend code
      run: cd ui && npm install && npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile.ui --tag chengtian/koala:latest
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push latest image
      run: docker push chengtian/koala:latest
    - name: Push the docker image
      run: export v=$(date +%s) && docker tag chengtian/koala:latest chengtian/koala:alpha-$v && docker push chengtian/koala:alpha-$v
